execute @e[type=astral:deus_head] ~ ~ ~ execute @e[type=astral:deus_ring_1, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_head]
execute @e[type=astral:deus_ring_1] ~ ~ ~ execute @e[type=astral:deus_bomber_1, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_ring_1]
execute @e[type=astral:deus_bomber_1] ~ ~ ~ execute @e[type=astral:deus_ring_2, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_bomber_1]
execute @e[type=astral:deus_ring_2] ~ ~ ~ execute @e[type=astral:deus_bomber_2, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_ring_2]
execute @e[type=astral:deus_bomber_2] ~ ~ ~ execute @e[type=astral:deus_ring_3, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_bomber_2]
execute @e[type=astral:deus_ring_3] ~ ~ ~ execute @e[type=astral:deus_bomber_3, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_ring_3]
execute @e[type=astral:deus_bomber_3] ~ ~ ~ execute @e[type=astral:deus_ring_4, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_bomber_3]
execute @e[type=astral:deus_ring_4] ~ ~ ~ execute @e[type=astral:deus_bomber_4, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_ring_4]
execute @e[type=astral:deus_bomber_4] ~ ~ ~ execute @e[type=astral:deus_tail, rm=1.2] ~ ~ ~ tp @s ^ ^ ^0.3 facing @e[type=astral:deus_bomber_4]

execute @e[type=astral:deus_head] ~ ~ ~ execute @e[type=astral:deus_ring_1] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_head]
execute @e[type=astral:deus_ring_1] ~ ~ ~ execute @e[type=astral:deus_bomber_1] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_ring_1]
execute @e[type=astral:deus_bomber_1] ~ ~ ~ execute @e[type=astral:deus_ring_2] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_bomber_1]
execute @e[type=astral:deus_ring_2] ~ ~ ~ execute @e[type=astral:deus_bomber_2] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_ring_2]
execute @e[type=astral:deus_bomber_2] ~ ~ ~ execute @e[type=astral:deus_ring_3] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_bomber_2]
execute @e[type=astral:deus_ring_3] ~ ~ ~ execute @e[type=astral:deus_bomber_3] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_ring_3]
execute @e[type=astral:deus_bomber_3] ~ ~ ~ execute @e[type=astral:deus_ring_4] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_bomber_3]
execute @e[type=astral:deus_ring_4] ~ ~ ~ execute @e[type=astral:deus_bomber_4] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_ring_4]
execute @e[type=astral:deus_bomber_4] ~ ~ ~ execute @e[type=astral:deus_tail] ~ ~ ~ tp @s ^ ^ ^ facing @e[type=astral:deus_bomber_4]
